---
title: "Random network scoring"
output: html_document
---

# Random generation of a network, sampling of a dataset and network score testing 

```{r init}
library(psoho)
library(bnlearn)
library(data.table)
```

```{r generation}
ordering <- c("A", "B", "C", "D", "E")
size <- 3

set.seed(4242)
ps <- Position$new(NULL, size, ordering)

dt = data.table(A_t_2 = rnorm(10000, 2.9, 2.7),
               B_t_2 = rnorm(10000, 1.2, 0.3),
               C_t_2 = rnorm(10000, 1.2, 1.9),
               D_t_2 = rnorm(10000, 3.7, 1.5),
               E_t_2 = rnorm(10000, 1.7, 0.6),
               A_t_1 = rnorm(10000, 2.8, 2.6),
               B_t_1 = rnorm(10000, 1.3, 0.5),
               C_t_1 = rnorm(10000, 1.5, 2),
               D_t_1 = rnorm(10000, 3.6, 1.6),
               E_t_1 = rnorm(10000, 1.7, 0.7),
               A_t_0 = rnorm(10000, 2.8, 2.6),
               B_t_0 = rnorm(10000, 1.3, 0.5),
               C_t_0 = rnorm(10000, 1.5, 2),
               D_t_0 = rnorm(10000, 3.6, 1.6),
               E_t_0 = rnorm(10000, 1.7, 0.7))

dt[, A_t_0 := A_t_0 + (-0.29) * C_t_2 + 1.3 * B_t_1]
dt[, B_t_0 := B_t_0 + 0.14 * C_t_2 + 0.87 * E_t_2 + (-0.7) * A_t_1]
dt[, C_t_0 := C_t_0 + 1.3 * C_t_1 + -(0.3) * B_t_1]
dt[, D_t_0 := D_t_0 + 0.37 * A_t_2 + 1.1 * D_t_1]
dt[, E_t_0 := E_t_0 + 0.21 * D_t_2 + 0.63 * A_t_1 + (-0.7) * C_t_1 + 0.2 * D_t_1]

struct <- ps$bn_translate()

print(bnlearn::score(struct, dt, type = "bge"))

```

A network representing the real structure that generated the data obtains a bge score of 23.7k, while randomly generated networks get bge values around the -27k mark.

```{r psoho}

eval_sol <- function(real, sol){
  real_arcs <- apply(real$arcs, 1, function(x){paste0(x[1], x[2])})
  sol_arcs <- apply(sol$arcs, 1, function(x){paste0(x[1], x[2])})
  
  return(sum(real_arcs %in% sol_arcs))
}

a <- Sys.time()
res <- psoho::learn_dbn_structure_pso(dt, size, n_inds = 200, n_it = 10,
                                      in_cte = 0.8, gb_cte = 0.5, lb_cte = 0.5)
eval_sol(struct, res)
print(Sys.time() - a)
```

