# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a causal list from a DBN. This is the C++ backend of the function.
#' 
#' @param net a dbn object treated as a list of lists
#' @param size the size of the DBN
#' @param ordering a list with the order of the variables in t_0
#' @return a list with a CharacterVector and a NumericVector
create_causlist_cpp <- function(net, size, ordering) {
    .Call('_psoho_create_causlist_cpp', PACKAGE = 'psoho', net, size, ordering)
}

#' Create a matrix with the arcs defined in a causlist object
#' 
#' @param cl a causal list
#' @param ordering a list with the order of the variables in t_0
#' @param counters the number of elements in each causal unit of the causality list
#' @param rows number of arcs in the network
#' @return a list with a CharacterVector and a NumericVector
cl_to_arc_matrix_cpp <- function(cl, ordering, counters, rows) {
    .Call('_psoho_cl_to_arc_matrix_cpp', PACKAGE = 'psoho', cl, ordering, counters, rows)
}

#' Return a list of nodes with the time slice appended up to the desired size
#' of the network
#' 
#' @param nodes a list with the names of the nodes in the network
#' @param size the size of the DBN
#' @return a list with the renamed nodes in each timeslice
rename_nodes_cpp <- function(nodes, size) {
    .Call('_psoho_rename_nodes_cpp', PACKAGE = 'psoho', nodes, size)
}

#' Create a velocity list and initialize it
#' 
#' @param ordering a list with the order of the variables in t_0
#' @param size the size of the DBN
#' @return a velocity list
initialize_vl_cpp <- function(ordering, size) {
    .Call('_psoho_initialize_vl_cpp', PACKAGE = 'psoho', ordering, size)
}

